modLoader="javafml"
loaderVersion="[47,)"
license="Apache License version 2.0"

[[mods]]
modId="sololeveling"
version="1.0.0"
displayName="SoloCraftReawakening"
displayURL="https://discord.gg/U3RtGxd5uw"
logoFile="logo.png"
credits="efkrdnz"
authors="efkrdnz"
description="Solo Craft: Reawakening by Efkrdnz (still under developement)"

[[dependencies.sololeveling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.sololeveling]]
    modId="kiwi"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="bettercombat"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="loquat"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="world_preview"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="cloth-config"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="world_edit"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="clothconfig"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="structure_gel_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="huge_structure_blocks"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sololeveling]]
    modId="particlepresets"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

