modLoader="javafml"
loaderVersion="[1,)"
license="Apache-2.0"

[[mods]]
modId="sololeveling"
version="1.3.1"
displayName="SoloCraft: Reawakening"
displayURL="https://discord.gg/U3RtGxd5uw"
logoFile="logo.png"
credits="efkrdnz"
authors="efkrdnz"
description='''
Solo Craft: Reawakening by Efkrdnz (still under development).
'''

[[mixins]]
config="mixins.sololeveling.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.sololeveling]]
modId="neoforge"
type="required"
versionRange="[21.1.244,)"
ordering="NONE"
side="BOTH"

[[dependencies.sololeveling]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.sololeveling]]
modId="geckolib"
type="required"
versionRange="[4.9.2,5)"
ordering="AFTER"
side="BOTH"

[[dependencies.sololeveling]]
modId="sodium"
type="optional"
versionRange="[0.6.13,0.9)"
ordering="NONE"
side="CLIENT"

[[dependencies.sololeveling]]
modId="iris"
type="optional"
versionRange="[1.8,1.9)"
ordering="AFTER"
side="CLIENT"

[[dependencies.sololeveling]]
modId="bettercombat"
type="optional"
versionRange="[2.4,3)"
ordering="AFTER"
side="BOTH"
