package net.solocraft.init;

import net.solocraft.potion.WillpowerCooldownMobEffect;
import net.solocraft.potion.WillPowerMobEffect;
import net.solocraft.potion.WaterBulletCooldownMobEffect;
import net.solocraft.potion.UsingFireMobEffect;
import net.solocraft.potion.UpforceSlashCooldownMobEffect;
import net.solocraft.potion.TrapCooldownMobEffect;
import net.solocraft.potion.TiemrMobEffect;
import net.solocraft.potion.TelekinesisCooldownMobEffect;
import net.solocraft.potion.TauntCooldownMobEffect;
import net.solocraft.potion.TankInvCooldownMobEffect;
import net.solocraft.potion.SwordOfLightMobEffect;
import net.solocraft.potion.SwordEnhanceMobEffect;
import net.solocraft.potion.SwordDanceMobEffect;
import net.solocraft.potion.SwordDanceCooldownMobEffect;
import net.solocraft.potion.StealthCooldownMobEffect;
import net.solocraft.potion.SpearCreationCooldownMobEffect;
import net.solocraft.potion.ShieldBashEffectMobEffect;
import net.solocraft.potion.ShieldBashCooldownMobEffect;
import net.solocraft.potion.ShadowStepCooldownMobEffect;
import net.solocraft.potion.ScreenShakeMobEffect;
import net.solocraft.potion.SOLcooldownMobEffect;
import net.solocraft.potion.QuickSlashesCooldownMobEffect;
import net.solocraft.potion.PhysicalBuffMobEffect;
import net.solocraft.potion.PhysicalBuffCooldownMobEffect;
import net.solocraft.potion.ParalyzeMobEffect;
import net.solocraft.potion.ParalyzeCooldownMobEffect;
import net.solocraft.potion.OverHealEffectMobEffect;
import net.solocraft.potion.OverHealCooldownMobEffect;
import net.solocraft.potion.OverHealAOEMobEffect;
import net.solocraft.potion.NoFallDamageMobEffect;
import net.solocraft.potion.MutilationStatusEffectMobEffect;
import net.solocraft.potion.MasteryCooldownMobEffect;
import net.solocraft.potion.ManaRefleshCooldownMobEffect;
import net.solocraft.potion.LightballCooldownMobEffect;
import net.solocraft.potion.LevDaggerCooldownMobEffect;
import net.solocraft.potion.LeapCooldownMobEffect;
import net.solocraft.potion.KamishcoolMobEffect;
import net.solocraft.potion.JobCooldown4MobEffect;
import net.solocraft.potion.JobCooldown3MobEffect;
import net.solocraft.potion.JobCooldown2MobEffect;
import net.solocraft.potion.JobCooldown1MobEffect;
import net.solocraft.potion.ImpactRushCooldownMobEffect;
import net.solocraft.potion.HomingFlameCooldownMobEffect;
import net.solocraft.potion.HeavyImpactCooldownMobEffect;
import net.solocraft.potion.HealingBeamCooldownMobEffect;
import net.solocraft.potion.HawkeyeCooldownMobEffect;
import net.solocraft.potion.HasteBuffMobEffect;
import net.solocraft.potion.HasteBuffCooldownMobEffect;
import net.solocraft.potion.GolemTeleportCooldownMobEffect;
import net.solocraft.potion.GolemKickCooldownMobEffect;
import net.solocraft.potion.FreezeMobEffect;
import net.solocraft.potion.FragOfProtectionCooldownMobEffect;
import net.solocraft.potion.FortifyMobEffect;
import net.solocraft.potion.FocusCooldownMobEffect;
import net.solocraft.potion.FatigueCooldownMobEffect;
import net.solocraft.potion.ElderBeastCooldownMobEffect;
import net.solocraft.potion.DualWieldingMobEffect;
import net.solocraft.potion.DualWieldingCooldownMobEffect;
import net.solocraft.potion.DomainBoostMobEffect;
import net.solocraft.potion.DetectionCooldownMobEffect;
import net.solocraft.potion.DashcooldownMobEffect;
import net.solocraft.potion.DanceCooldownMobEffect;
import net.solocraft.potion.DaggerRushCooldownMobEffect;
import net.solocraft.potion.CursedChainsCooldownMobEffect;
import net.solocraft.potion.CurseSmokeCooldownMobEffect;
import net.solocraft.potion.CrossAttackCooldownMobEffect;
import net.solocraft.potion.CriticalStrikeCooldownMobEffect;
import net.solocraft.potion.CounterCooldownMobEffect;
import net.solocraft.potion.CooldownSOFFMobEffect;
import net.solocraft.potion.ConsecutiveSlashesMobEffect;
import net.solocraft.potion.BloodlustCooldownMobEffect;
import net.solocraft.potion.BleedMobEffect;
import net.solocraft.potion.BellOfHealingCooldownMobEffect;
import net.solocraft.potion.BackstabCooldownMobEffect;
import net.solocraft.potion.AuraMobEffect;
import net.solocraft.potion.AuraCooldownMobEffect;
import net.solocraft.potion.ArrowRainCooldownMobEffect;
import net.solocraft.potion.AriseCooldownMobEffect;
import net.solocraft.potion.AirVacuumCooldwonMobEffect;
import net.solocraft.SololevelingMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.effect.MobEffect;

public class SololevelingModMobEffects {
	public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(ForgeRegistries.MOB_EFFECTS, SololevelingMod.MODID);
	public static final RegistryObject<MobEffect> PARALYZE = REGISTRY.register("paralyze", () -> new ParalyzeMobEffect());
	public static final RegistryObject<MobEffect> BLEED = REGISTRY.register("bleed", () -> new BleedMobEffect());
	public static final RegistryObject<MobEffect> COOLDOWN_SOFF = REGISTRY.register("cooldown_soff", () -> new CooldownSOFFMobEffect());
	public static final RegistryObject<MobEffect> PARALYZE_COOLDOWN = REGISTRY.register("paralyze_cooldown", () -> new ParalyzeCooldownMobEffect());
	public static final RegistryObject<MobEffect> DAGGER_RUSH_COOLDOWN = REGISTRY.register("dagger_rush_cooldown", () -> new DaggerRushCooldownMobEffect());
	public static final RegistryObject<MobEffect> SWORD_ENHANCE = REGISTRY.register("sword_enhance", () -> new SwordEnhanceMobEffect());
	public static final RegistryObject<MobEffect> KAMISHCOOL = REGISTRY.register("kamishcool", () -> new KamishcoolMobEffect());
	public static final RegistryObject<MobEffect> COUNTER_COOLDOWN = REGISTRY.register("counter_cooldown", () -> new CounterCooldownMobEffect());
	public static final RegistryObject<MobEffect> STEALTH_COOLDOWN = REGISTRY.register("stealth_cooldown", () -> new StealthCooldownMobEffect());
	public static final RegistryObject<MobEffect> BLOODLUST_COOLDOWN = REGISTRY.register("bloodlust_cooldown", () -> new BloodlustCooldownMobEffect());
	public static final RegistryObject<MobEffect> WATER_BULLET_COOLDOWN = REGISTRY.register("water_bullet_cooldown", () -> new WaterBulletCooldownMobEffect());
	public static final RegistryObject<MobEffect> IMPACT_RUSH_COOLDOWN = REGISTRY.register("impact_rush_cooldown", () -> new ImpactRushCooldownMobEffect());
	public static final RegistryObject<MobEffect> HEAVY_IMPACT_COOLDOWN = REGISTRY.register("heavy_impact_cooldown", () -> new HeavyImpactCooldownMobEffect());
	public static final RegistryObject<MobEffect> ARISE_COOLDOWN = REGISTRY.register("arise_cooldown", () -> new AriseCooldownMobEffect());
	public static final RegistryObject<MobEffect> CONSECUTIVE_SLASHES = REGISTRY.register("consecutive_slashes", () -> new ConsecutiveSlashesMobEffect());
	public static final RegistryObject<MobEffect> TANK_INV_COOLDOWN = REGISTRY.register("tank_inv_cooldown", () -> new TankInvCooldownMobEffect());
	public static final RegistryObject<MobEffect> FRAG_OF_PROTECTION_COOLDOWN = REGISTRY.register("frag_of_protection_cooldown", () -> new FragOfProtectionCooldownMobEffect());
	public static final RegistryObject<MobEffect> LEAP_COOLDOWN = REGISTRY.register("leap_cooldown", () -> new LeapCooldownMobEffect());
	public static final RegistryObject<MobEffect> HEALING_BEAM_COOLDOWN = REGISTRY.register("healing_beam_cooldown", () -> new HealingBeamCooldownMobEffect());
	public static final RegistryObject<MobEffect> OVER_HEAL_EFFECT = REGISTRY.register("over_heal_effect", () -> new OverHealEffectMobEffect());
	public static final RegistryObject<MobEffect> OVER_HEAL_COOLDOWN = REGISTRY.register("over_heal_cooldown", () -> new OverHealCooldownMobEffect());
	public static final RegistryObject<MobEffect> BELL_OF_HEALING_COOLDOWN = REGISTRY.register("bell_of_healing_cooldown", () -> new BellOfHealingCooldownMobEffect());
	public static final RegistryObject<MobEffect> MANA_REFLESH_COOLDOWN = REGISTRY.register("mana_reflesh_cooldown", () -> new ManaRefleshCooldownMobEffect());
	public static final RegistryObject<MobEffect> USING_FIRE = REGISTRY.register("using_fire", () -> new UsingFireMobEffect());
	public static final RegistryObject<MobEffect> HOMING_FLAME_COOLDOWN = REGISTRY.register("homing_flame_cooldown", () -> new HomingFlameCooldownMobEffect());
	public static final RegistryObject<MobEffect> LEV_DAGGER_COOLDOWN = REGISTRY.register("lev_dagger_cooldown", () -> new LevDaggerCooldownMobEffect());
	public static final RegistryObject<MobEffect> TELEKINESIS_COOLDOWN = REGISTRY.register("telekinesis_cooldown", () -> new TelekinesisCooldownMobEffect());
	public static final RegistryObject<MobEffect> AIR_VACUUM_COOLDWON = REGISTRY.register("air_vacuum_cooldwon", () -> new AirVacuumCooldwonMobEffect());
	public static final RegistryObject<MobEffect> JOB_COOLDOWN_1 = REGISTRY.register("job_cooldown_1", () -> new JobCooldown1MobEffect());
	public static final RegistryObject<MobEffect> JOB_COOLDOWN_2 = REGISTRY.register("job_cooldown_2", () -> new JobCooldown2MobEffect());
	public static final RegistryObject<MobEffect> JOB_COOLDOWN_3 = REGISTRY.register("job_cooldown_3", () -> new JobCooldown3MobEffect());
	public static final RegistryObject<MobEffect> JOB_COOLDOWN_4 = REGISTRY.register("job_cooldown_4", () -> new JobCooldown4MobEffect());
	public static final RegistryObject<MobEffect> CROSS_ATTACK_COOLDOWN = REGISTRY.register("cross_attack_cooldown", () -> new CrossAttackCooldownMobEffect());
	public static final RegistryObject<MobEffect> DOMAIN_BOOST = REGISTRY.register("domain_boost", () -> new DomainBoostMobEffect());
	public static final RegistryObject<MobEffect> AURA = REGISTRY.register("aura", () -> new AuraMobEffect());
	public static final RegistryObject<MobEffect> DUAL_WIELDING = REGISTRY.register("dual_wielding", () -> new DualWieldingMobEffect());
	public static final RegistryObject<MobEffect> TIEMR = REGISTRY.register("tiemr", () -> new TiemrMobEffect());
	public static final RegistryObject<MobEffect> ELDER_BEAST_COOLDOWN = REGISTRY.register("elder_beast_cooldown", () -> new ElderBeastCooldownMobEffect());
	public static final RegistryObject<MobEffect> LIGHTBALL_COOLDOWN = REGISTRY.register("lightball_cooldown", () -> new LightballCooldownMobEffect());
	public static final RegistryObject<MobEffect> DETECTION_COOLDOWN = REGISTRY.register("detection_cooldown", () -> new DetectionCooldownMobEffect());
	public static final RegistryObject<MobEffect> UPFORCE_SLASH_COOLDOWN = REGISTRY.register("upforce_slash_cooldown", () -> new UpforceSlashCooldownMobEffect());
	public static final RegistryObject<MobEffect> QUICK_SLASHES_COOLDOWN = REGISTRY.register("quick_slashes_cooldown", () -> new QuickSlashesCooldownMobEffect());
	public static final RegistryObject<MobEffect> SHIELD_BASH_EFFECT = REGISTRY.register("shield_bash_effect", () -> new ShieldBashEffectMobEffect());
	public static final RegistryObject<MobEffect> NO_FALL_DAMAGE = REGISTRY.register("no_fall_damage", () -> new NoFallDamageMobEffect());
	public static final RegistryObject<MobEffect> SWORD_OF_LIGHT = REGISTRY.register("sword_of_light", () -> new SwordOfLightMobEffect());
	public static final RegistryObject<MobEffect> SWORD_DANCE = REGISTRY.register("sword_dance", () -> new SwordDanceMobEffect());
	public static final RegistryObject<MobEffect> DANCE_COOLDOWN = REGISTRY.register("dance_cooldown", () -> new DanceCooldownMobEffect());
	public static final RegistryObject<MobEffect> SO_LCOOLDOWN = REGISTRY.register("so_lcooldown", () -> new SOLcooldownMobEffect());
	public static final RegistryObject<MobEffect> OVER_HEAL_AOE = REGISTRY.register("over_heal_aoe", () -> new OverHealAOEMobEffect());
	public static final RegistryObject<MobEffect> PHYSICAL_BUFF = REGISTRY.register("physical_buff", () -> new PhysicalBuffMobEffect());
	public static final RegistryObject<MobEffect> HASTE_BUFF = REGISTRY.register("haste_buff", () -> new HasteBuffMobEffect());
	public static final RegistryObject<MobEffect> PHYSICAL_BUFF_COOLDOWN = REGISTRY.register("physical_buff_cooldown", () -> new PhysicalBuffCooldownMobEffect());
	public static final RegistryObject<MobEffect> HASTE_BUFF_COOLDOWN = REGISTRY.register("haste_buff_cooldown", () -> new HasteBuffCooldownMobEffect());
	public static final RegistryObject<MobEffect> WILL_POWER = REGISTRY.register("will_power", () -> new WillPowerMobEffect());
	public static final RegistryObject<MobEffect> AURA_COOLDOWN = REGISTRY.register("aura_cooldown", () -> new AuraCooldownMobEffect());
	public static final RegistryObject<MobEffect> SHADOW_STEP_COOLDOWN = REGISTRY.register("shadow_step_cooldown", () -> new ShadowStepCooldownMobEffect());
	public static final RegistryObject<MobEffect> DUAL_WIELDING_COOLDOWN = REGISTRY.register("dual_wielding_cooldown", () -> new DualWieldingCooldownMobEffect());
	public static final RegistryObject<MobEffect> BACKSTAB_COOLDOWN = REGISTRY.register("backstab_cooldown", () -> new BackstabCooldownMobEffect());
	public static final RegistryObject<MobEffect> SWORD_DANCE_COOLDOWN = REGISTRY.register("sword_dance_cooldown", () -> new SwordDanceCooldownMobEffect());
	public static final RegistryObject<MobEffect> WILLPOWER_COOLDOWN = REGISTRY.register("willpower_cooldown", () -> new WillpowerCooldownMobEffect());
	public static final RegistryObject<MobEffect> SHIELD_BASH_COOLDOWN = REGISTRY.register("shield_bash_cooldown", () -> new ShieldBashCooldownMobEffect());
	public static final RegistryObject<MobEffect> TAUNT_COOLDOWN = REGISTRY.register("taunt_cooldown", () -> new TauntCooldownMobEffect());
	public static final RegistryObject<MobEffect> FREEZE = REGISTRY.register("freeze", () -> new FreezeMobEffect());
	public static final RegistryObject<MobEffect> GOLEM_TELEPORT_COOLDOWN = REGISTRY.register("golem_teleport_cooldown", () -> new GolemTeleportCooldownMobEffect());
	public static final RegistryObject<MobEffect> GOLEM_KICK_COOLDOWN = REGISTRY.register("golem_kick_cooldown", () -> new GolemKickCooldownMobEffect());
	public static final RegistryObject<MobEffect> TRAP_COOLDOWN = REGISTRY.register("trap_cooldown", () -> new TrapCooldownMobEffect());
	public static final RegistryObject<MobEffect> HAWKEYE_COOLDOWN = REGISTRY.register("hawkeye_cooldown", () -> new HawkeyeCooldownMobEffect());
	public static final RegistryObject<MobEffect> FOCUS_COOLDOWN = REGISTRY.register("focus_cooldown", () -> new FocusCooldownMobEffect());
	public static final RegistryObject<MobEffect> ARROW_RAIN_COOLDOWN = REGISTRY.register("arrow_rain_cooldown", () -> new ArrowRainCooldownMobEffect());
	public static final RegistryObject<MobEffect> SPEAR_CREATION_COOLDOWN = REGISTRY.register("spear_creation_cooldown", () -> new SpearCreationCooldownMobEffect());
	public static final RegistryObject<MobEffect> SCREEN_SHAKE = REGISTRY.register("screen_shake", () -> new ScreenShakeMobEffect());
	public static final RegistryObject<MobEffect> DASHCOOLDOWN = REGISTRY.register("dashcooldown", () -> new DashcooldownMobEffect());
	public static final RegistryObject<MobEffect> FATIGUE_COOLDOWN = REGISTRY.register("fatigue_cooldown", () -> new FatigueCooldownMobEffect());
	public static final RegistryObject<MobEffect> MASTERY_COOLDOWN = REGISTRY.register("mastery_cooldown", () -> new MasteryCooldownMobEffect());
	public static final RegistryObject<MobEffect> CURSE_SMOKE_COOLDOWN = REGISTRY.register("curse_smoke_cooldown", () -> new CurseSmokeCooldownMobEffect());
	public static final RegistryObject<MobEffect> CURSED_CHAINS_COOLDOWN = REGISTRY.register("cursed_chains_cooldown", () -> new CursedChainsCooldownMobEffect());
	public static final RegistryObject<MobEffect> CRITICAL_STRIKE_COOLDOWN = REGISTRY.register("critical_strike_cooldown", () -> new CriticalStrikeCooldownMobEffect());
	public static final RegistryObject<MobEffect> MUTILATION_STATUS_EFFECT = REGISTRY.register("mutilation_status_effect", () -> new MutilationStatusEffectMobEffect());
	public static final RegistryObject<MobEffect> FORTIFY = REGISTRY.register("fortify", () -> new FortifyMobEffect());
}
