package net.solocraft.init;

import net.solocraft.potion.ChillMobEffect;
import net.solocraft.potion.CurseMobEffect;
import net.solocraft.util.CurseType;
import net.solocraft.potion.VeilShroudMobEffect;
import net.solocraft.potion.WillpowerCooldownMobEffect;
import net.solocraft.potion.WillPowerMobEffect;
import net.solocraft.potion.WaterBulletCooldownMobEffect;
import net.solocraft.potion.UsingFireMobEffect;
import net.solocraft.potion.UpforceSlashCooldownMobEffect;
import net.solocraft.potion.TrapCooldownMobEffect;
import net.solocraft.potion.TiemrMobEffect;
import net.solocraft.potion.TelekinesisCooldownMobEffect;
import net.solocraft.potion.TauntCooldownMobEffect;
import net.solocraft.potion.TankInvCooldownMobEffect;
import net.solocraft.potion.SwordOfLightMobEffect;
import net.solocraft.potion.SwordEnhanceMobEffect;
import net.solocraft.potion.SwordDanceMobEffect;
import net.solocraft.potion.SwordDanceCooldownMobEffect;
import net.solocraft.potion.StealthCooldownMobEffect;
import net.solocraft.potion.SpearCreationCooldownMobEffect;
import net.solocraft.potion.ShieldBashEffectMobEffect;
import net.solocraft.potion.ShieldBashCooldownMobEffect;
import net.solocraft.potion.ShadowStepCooldownMobEffect;
import net.solocraft.potion.ScreenShakeMobEffect;
import net.solocraft.potion.SOLcooldownMobEffect;
import net.solocraft.potion.QuickSlashesCooldownMobEffect;
import net.solocraft.potion.PhysicalBuffMobEffect;
import net.solocraft.potion.PhysicalBuffCooldownMobEffect;
import net.solocraft.potion.ParalyzeMobEffect;
import net.solocraft.potion.ParalyzeCooldownMobEffect;
import net.solocraft.potion.OverHealEffectMobEffect;
import net.solocraft.potion.OverHealCooldownMobEffect;
import net.solocraft.potion.OverHealAOEMobEffect;
import net.solocraft.potion.NoFallDamageMobEffect;
import net.solocraft.potion.MutilationStatusEffectMobEffect;
import net.solocraft.potion.MasteryCooldownMobEffect;
import net.solocraft.potion.ManaRefleshCooldownMobEffect;
import net.solocraft.potion.LightballCooldownMobEffect;
import net.solocraft.potion.LevDaggerCooldownMobEffect;
import net.solocraft.potion.LeapCooldownMobEffect;
import net.solocraft.potion.KamishcoolMobEffect;
import net.solocraft.potion.JobCooldown4MobEffect;
import net.solocraft.potion.JobCooldown3MobEffect;
import net.solocraft.potion.JobCooldown2MobEffect;
import net.solocraft.potion.JobCooldown1MobEffect;
import net.solocraft.potion.ImpactRushCooldownMobEffect;
import net.solocraft.potion.HomingFlameCooldownMobEffect;
import net.solocraft.potion.HeavyImpactCooldownMobEffect;
import net.solocraft.potion.HealingBeamCooldownMobEffect;
import net.solocraft.potion.HawkeyeCooldownMobEffect;
import net.solocraft.potion.HasteBuffMobEffect;
import net.solocraft.potion.HasteBuffCooldownMobEffect;
import net.solocraft.potion.GolemTeleportCooldownMobEffect;
import net.solocraft.potion.GolemKickCooldownMobEffect;
import net.solocraft.potion.FreezeMobEffect;
import net.solocraft.potion.FragOfProtectionCooldownMobEffect;
import net.solocraft.potion.FortifyMobEffect;
import net.solocraft.potion.FocusCooldownMobEffect;
import net.solocraft.potion.FatigueCooldownMobEffect;
import net.solocraft.potion.ElderBeastCooldownMobEffect;
import net.solocraft.potion.DualWieldingMobEffect;
import net.solocraft.potion.DualWieldingCooldownMobEffect;
import net.solocraft.potion.DomainBoostMobEffect;
import net.solocraft.potion.DetectionCooldownMobEffect;
import net.solocraft.potion.DashcooldownMobEffect;
import net.solocraft.potion.DanceCooldownMobEffect;
import net.solocraft.potion.DaggerRushCooldownMobEffect;
import net.solocraft.potion.CursedChainsCooldownMobEffect;
import net.solocraft.potion.CurseSmokeCooldownMobEffect;
import net.solocraft.potion.CrossAttackCooldownMobEffect;
import net.solocraft.potion.CriticalStrikeCooldownMobEffect;
import net.solocraft.potion.CounterCooldownMobEffect;
import net.solocraft.potion.CooldownSOFFMobEffect;
import net.solocraft.potion.ConsecutiveSlashesMobEffect;
import net.solocraft.potion.BloodlustCooldownMobEffect;
import net.solocraft.potion.BleedMobEffect;
import net.solocraft.potion.BellOfHealingCooldownMobEffect;
import net.solocraft.potion.BackstabCooldownMobEffect;
import net.solocraft.potion.AuraMobEffect;
import net.solocraft.potion.AuraCooldownMobEffect;
import net.solocraft.potion.ArrowRainCooldownMobEffect;
import net.solocraft.potion.AriseCooldownMobEffect;
import net.solocraft.potion.AirVacuumCooldwonMobEffect;
import net.solocraft.SololevelingMod;

import net.neoforged.neoforge.registries.DeferredHolder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.neoforged.neoforge.registries.DeferredRegister;

import net.minecraft.world.effect.MobEffect;

public class SololevelingModMobEffects {
	public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(BuiltInRegistries.MOB_EFFECT, SololevelingMod.MODID);
	public static final DeferredHolder<MobEffect, MobEffect> PARALYZE = REGISTRY.register("paralyze", () -> new ParalyzeMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BLEED = REGISTRY.register("bleed", () -> new BleedMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> COOLDOWN_SOFF = REGISTRY.register("cooldown_soff", () -> new CooldownSOFFMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> PARALYZE_COOLDOWN = REGISTRY.register("paralyze_cooldown", () -> new ParalyzeCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DAGGER_RUSH_COOLDOWN = REGISTRY.register("dagger_rush_cooldown", () -> new DaggerRushCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SWORD_ENHANCE = REGISTRY.register("sword_enhance", () -> new SwordEnhanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> KAMISHCOOL = REGISTRY.register("kamishcool", () -> new KamishcoolMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> COUNTER_COOLDOWN = REGISTRY.register("counter_cooldown", () -> new CounterCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> STEALTH_COOLDOWN = REGISTRY.register("stealth_cooldown", () -> new StealthCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BLOODLUST_COOLDOWN = REGISTRY.register("bloodlust_cooldown", () -> new BloodlustCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WATER_BULLET_COOLDOWN = REGISTRY.register("water_bullet_cooldown", () -> new WaterBulletCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> IMPACT_RUSH_COOLDOWN = REGISTRY.register("impact_rush_cooldown", () -> new ImpactRushCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HEAVY_IMPACT_COOLDOWN = REGISTRY.register("heavy_impact_cooldown", () -> new HeavyImpactCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ARISE_COOLDOWN = REGISTRY.register("arise_cooldown", () -> new AriseCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CONSECUTIVE_SLASHES = REGISTRY.register("consecutive_slashes", () -> new ConsecutiveSlashesMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TANK_INV_COOLDOWN = REGISTRY.register("tank_inv_cooldown", () -> new TankInvCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FRAG_OF_PROTECTION_COOLDOWN = REGISTRY.register("frag_of_protection_cooldown", () -> new FragOfProtectionCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LEAP_COOLDOWN = REGISTRY.register("leap_cooldown", () -> new LeapCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HEALING_BEAM_COOLDOWN = REGISTRY.register("healing_beam_cooldown", () -> new HealingBeamCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> OVER_HEAL_EFFECT = REGISTRY.register("over_heal_effect", () -> new OverHealEffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> OVER_HEAL_COOLDOWN = REGISTRY.register("over_heal_cooldown", () -> new OverHealCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BELL_OF_HEALING_COOLDOWN = REGISTRY.register("bell_of_healing_cooldown", () -> new BellOfHealingCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> MANA_REFLESH_COOLDOWN = REGISTRY.register("mana_reflesh_cooldown", () -> new ManaRefleshCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> USING_FIRE = REGISTRY.register("using_fire", () -> new UsingFireMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HOMING_FLAME_COOLDOWN = REGISTRY.register("homing_flame_cooldown", () -> new HomingFlameCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LEV_DAGGER_COOLDOWN = REGISTRY.register("lev_dagger_cooldown", () -> new LevDaggerCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TELEKINESIS_COOLDOWN = REGISTRY.register("telekinesis_cooldown", () -> new TelekinesisCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> AIR_VACUUM_COOLDWON = REGISTRY.register("air_vacuum_cooldwon", () -> new AirVacuumCooldwonMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> JOB_COOLDOWN_1 = REGISTRY.register("job_cooldown_1", () -> new JobCooldown1MobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> JOB_COOLDOWN_2 = REGISTRY.register("job_cooldown_2", () -> new JobCooldown2MobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> JOB_COOLDOWN_3 = REGISTRY.register("job_cooldown_3", () -> new JobCooldown3MobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> JOB_COOLDOWN_4 = REGISTRY.register("job_cooldown_4", () -> new JobCooldown4MobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CROSS_ATTACK_COOLDOWN = REGISTRY.register("cross_attack_cooldown", () -> new CrossAttackCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DOMAIN_BOOST = REGISTRY.register("domain_boost", () -> new DomainBoostMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> AURA = REGISTRY.register("aura", () -> new AuraMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DUAL_WIELDING = REGISTRY.register("dual_wielding", () -> new DualWieldingMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TIEMR = REGISTRY.register("tiemr", () -> new TiemrMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ELDER_BEAST_COOLDOWN = REGISTRY.register("elder_beast_cooldown", () -> new ElderBeastCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LIGHTBALL_COOLDOWN = REGISTRY.register("lightball_cooldown", () -> new LightballCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DETECTION_COOLDOWN = REGISTRY.register("detection_cooldown", () -> new DetectionCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> UPFORCE_SLASH_COOLDOWN = REGISTRY.register("upforce_slash_cooldown", () -> new UpforceSlashCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> QUICK_SLASHES_COOLDOWN = REGISTRY.register("quick_slashes_cooldown", () -> new QuickSlashesCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SHIELD_BASH_EFFECT = REGISTRY.register("shield_bash_effect", () -> new ShieldBashEffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> NO_FALL_DAMAGE = REGISTRY.register("no_fall_damage", () -> new NoFallDamageMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SWORD_OF_LIGHT = REGISTRY.register("sword_of_light", () -> new SwordOfLightMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> VEIL_SHROUD = REGISTRY.register("veil_shroud", () -> new VeilShroudMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CURSE_WITHERING = REGISTRY.register("curse_withering", () -> new CurseMobEffect(CurseType.WITHERING));
	public static final DeferredHolder<MobEffect, MobEffect> CURSE_ENFEEBLEMENT = REGISTRY.register("curse_enfeeblement", () -> new CurseMobEffect(CurseType.ENFEEBLEMENT));
	public static final DeferredHolder<MobEffect, MobEffect> CURSE_LEADEN = REGISTRY.register("curse_leaden", () -> new CurseMobEffect(CurseType.LEADEN));
	public static final DeferredHolder<MobEffect, MobEffect> CURSE_MANA_ROT = REGISTRY.register("curse_mana_rot", () -> new CurseMobEffect(CurseType.MANA_ROT));
	public static final DeferredHolder<MobEffect, MobEffect> CURSE_BLIGHT = REGISTRY.register("curse_blight", () -> new CurseMobEffect(CurseType.BLIGHT));
	public static final DeferredHolder<MobEffect, MobEffect> CURSE_DOOM = REGISTRY.register("curse_doom", () -> new CurseMobEffect(CurseType.DOOM));
	/** Ambient cold of Sillad's frozen domain; amplifier carries the stage. */
	public static final DeferredHolder<MobEffect, MobEffect> CHILL = REGISTRY.register("chill", () -> new ChillMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SWORD_DANCE = REGISTRY.register("sword_dance", () -> new SwordDanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DANCE_COOLDOWN = REGISTRY.register("dance_cooldown", () -> new DanceCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SO_LCOOLDOWN = REGISTRY.register("so_lcooldown", () -> new SOLcooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> OVER_HEAL_AOE = REGISTRY.register("over_heal_aoe", () -> new OverHealAOEMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> PHYSICAL_BUFF = REGISTRY.register("physical_buff", () -> new PhysicalBuffMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HASTE_BUFF = REGISTRY.register("haste_buff", () -> new HasteBuffMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> PHYSICAL_BUFF_COOLDOWN = REGISTRY.register("physical_buff_cooldown", () -> new PhysicalBuffCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HASTE_BUFF_COOLDOWN = REGISTRY.register("haste_buff_cooldown", () -> new HasteBuffCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WILL_POWER = REGISTRY.register("will_power", () -> new WillPowerMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> AURA_COOLDOWN = REGISTRY.register("aura_cooldown", () -> new AuraCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SHADOW_STEP_COOLDOWN = REGISTRY.register("shadow_step_cooldown", () -> new ShadowStepCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DUAL_WIELDING_COOLDOWN = REGISTRY.register("dual_wielding_cooldown", () -> new DualWieldingCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BACKSTAB_COOLDOWN = REGISTRY.register("backstab_cooldown", () -> new BackstabCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SWORD_DANCE_COOLDOWN = REGISTRY.register("sword_dance_cooldown", () -> new SwordDanceCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WILLPOWER_COOLDOWN = REGISTRY.register("willpower_cooldown", () -> new WillpowerCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SHIELD_BASH_COOLDOWN = REGISTRY.register("shield_bash_cooldown", () -> new ShieldBashCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TAUNT_COOLDOWN = REGISTRY.register("taunt_cooldown", () -> new TauntCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FREEZE = REGISTRY.register("freeze", () -> new FreezeMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GOLEM_TELEPORT_COOLDOWN = REGISTRY.register("golem_teleport_cooldown", () -> new GolemTeleportCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GOLEM_KICK_COOLDOWN = REGISTRY.register("golem_kick_cooldown", () -> new GolemKickCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TRAP_COOLDOWN = REGISTRY.register("trap_cooldown", () -> new TrapCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HAWKEYE_COOLDOWN = REGISTRY.register("hawkeye_cooldown", () -> new HawkeyeCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FOCUS_COOLDOWN = REGISTRY.register("focus_cooldown", () -> new FocusCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ARROW_RAIN_COOLDOWN = REGISTRY.register("arrow_rain_cooldown", () -> new ArrowRainCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SPEAR_CREATION_COOLDOWN = REGISTRY.register("spear_creation_cooldown", () -> new SpearCreationCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SCREEN_SHAKE = REGISTRY.register("screen_shake", () -> new ScreenShakeMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DASHCOOLDOWN = REGISTRY.register("dashcooldown", () -> new DashcooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FATIGUE_COOLDOWN = REGISTRY.register("fatigue_cooldown", () -> new FatigueCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> MASTERY_COOLDOWN = REGISTRY.register("mastery_cooldown", () -> new MasteryCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CURSE_SMOKE_COOLDOWN = REGISTRY.register("curse_smoke_cooldown", () -> new CurseSmokeCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CURSED_CHAINS_COOLDOWN = REGISTRY.register("cursed_chains_cooldown", () -> new CursedChainsCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CRITICAL_STRIKE_COOLDOWN = REGISTRY.register("critical_strike_cooldown", () -> new CriticalStrikeCooldownMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> MUTILATION_STATUS_EFFECT = REGISTRY.register("mutilation_status_effect", () -> new MutilationStatusEffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FORTIFY = REGISTRY.register("fortify", () -> new FortifyMobEffect());
}
